

site_name: Armbian Documentation

repo_url: https://github.com/lanefu/armbianDocsAndProcess
repo_name: Github

site_author: "Armbian team"

theme: readthedocs

markdown_extensions:
  - smarty
  - footnotes
  - toc:
      permalink: True

pages:
  - Home: index.md
  - 'Hardware' :
        - 'Allwinner' : 'Hardware_Allwinner.md'
        - 'Allwinner H3' : 'Hardware_Allwinner-H3.md'
    
  - 'Process' :
        - 'Armbian Task Tracking' : 'Process_Armbian-Task-Tracking.md'
        - 'Documentation' : 'Process_Documentation.md'
        - 'Contribute' : 'Process_Contribute.md'
    
  - 'Release' :
        - 'Changelog' : 'Release_Changelog.md'
        - 'Download' : 'Release_Download.md'
    
  - 'Developer Guide' :
        - 'FEL boot' : 'Developer-Guide_FEL-boot.md'
        - 'User Configurations' : 'Developer-Guide_User-Configurations.md'
        - 'Build Options' : 'Developer-Guide_Build-Options.md'
        - 'Build Preparation' : 'Developer-Guide_Build-Preparation.md'
        - 'Build Process' : 'Developer-Guide_Build-Process.md'
    
  - 'User Guide' :
        - 'Getting Started' : 'User-Guide_Getting-Started.md'
        - 'Advanced Features' : 'User-Guide_Advanced-Features.md'
        - 'Fine Tuning' : 'User-Guide_Fine-Tuning.md'
    

