

site_name: Armbian Documentation

repo_url: https://github.com/lanefu/armbianDocsAndProcess
repo_name: Github

site_author: "Armbian team"

theme: readthedocs

markdown_extensions:
  - smarty
  - footnotes
  - toc:
      permalink: True

pages:
  - Home: index.md
  - 'Hardware' :
        - 'Allwinner' : '_Hardware_Allwinner.md'
        - 'Allwinner H3' : '_Hardware_Allwinner-H3.md'
    
  - 'Process' :
        - 'Contribute' : '_Process_Contribute.md'
        - 'Documentation' : '_Process_Documentation.md'
        - 'Armbian Task Tracking' : '_Process_Armbian-Task-Tracking.md'
    
  - 'Release' :
        - 'Changelog' : '_Release_Changelog.md'
        - 'Download' : '_Release_Download.md'
    
  - 'Developer Guide' :
        - 'Build Options' : '_Developer-Guide_Build-Options.md'
        - 'Build Process' : '_Developer-Guide_Build-Process.md'
        - 'Feel boot' : '_Developer-Guide_Feel-boot.md'
        - 'Build Preparation' : '_Developer-Guide_Build-Preparation.md'
        - 'User Configurations' : '_Developer-Guide_User-Configurations.md'
    
  - 'User Guide' :
        - 'Fine Tuning' : '_User-Guide_Fine-Tuning.md'
        - 'Advanced Features' : '_User-Guide_Advanced-Features.md'
        - 'Getting Started' : '_User-Guide_Getting-Started.md'
    

